# Generated by Django 4.0.4 on 2022-05-03 11:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_news_date_consulting_center_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_posted',
            field=models.CharField(blank=True, default=api.models.special_date, max_length=100, verbose_name='date_posted'),
        ),
    ]
