# Generated by Django 4.0.4 on 2022-05-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_news_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting_center',
            name='region',
            field=models.CharField(blank=True, max_length=200, verbose_name='region'),
        ),
    ]
