# Generated by Django 3.2.9 on 2022-05-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220503_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting_center',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='title'),
        ),
    ]
