# Generated by Django 4.0.4 on 2022-05-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_consulting_center_title_consulting_center_website_and_more'),
        ('api', '0006_consulting_center_title'),
    ]

    operations = [
    ]
